### ISSUE TITLE
Additional Packages and Console.log error

### ISSUE THREAD

**Issue by ksafstrom** [Ruud14/MMM-SpotifyReleases#2]
Hello again.

Upon further poking through to get this module working locally.  After setting up the accesskey and refreshtoken.  Launching  MM, resulted in a black screen.  Logs indicated module `request-promise-native` was missing.  Once that was installed, another module not found was `xhr2`.  After that, I eventually needed to uncomment the console.log in MMM-SpotifyReleases.js to have the artist list populate in MM.  I'm not in a state to make a pull request to your README to include those edits but wanted to jot down the troubleshooting required to get this to function.

Thanks!

**Comment by Ruud14** [comment]
Thanks for letting me know!

It is been a while since I've looked at this repo to be honest.
I will reinstall the module on my own magic mirror so I can see what is not documented etc. 
After that I'll update the README accordingly.
